services:
  - type: web
    name: tr-placement-calculator
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12