services:
  # Web service
  - type: web
    name: tr-placement-calculator
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Ensure template and static directories exist
      mkdir -p templates static
      # Copy files if they exist in app directory
      [ -d "app/templates" ] && cp -r app/templates/* templates/ || echo "No app/templates directory"
      [ -d "app/static" ] && cp -r app/static/* static/ || echo "No app/static directory"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    healthCheckPath: / 